[package]
name = "pentair_esp32"
version = "0.1.0"
authors = ["Your Name <you@example.com>"]
edition = "2021"

[profile.release]
opt-level = "s"

[profile.dev]
debug = true    # Symbols are nice and they don't increase the size on Flash too much
opt-level = "z"

[features]
default = ["std", "experimental"]
std = ["esp-idf-sys/std"]
alloc = ["esp-idf-sys/alloc"]
experimental = ["esp-idf-sys/experimental"]
nightly = ["esp-idf-sys/nightly"]
native = ["esp-idf-sys/native"]

[dependencies]
esp-idf-sys = { version = "0.33", features = ["binstart"] }
esp-idf-hal = "0.42"
esp-idf-svc = { version = "0.42", features = ["experimental", "ws"] }
embedded-svc = { version = "0.26", features = ["ws"] }
log = "0.4"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
embedded-hal = "0.2.7"
heapless = { version = "0.7", default-features = false }
ufmt = "0.5"
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }

embassy-sync = { version = "0.5", features = ["std", "log"] }
embassy-time = { version = "0.2", features = ["std", "log"] }
embassy-executor = { version = "0.5", features = ["nightly", "integrated-timers", "executor-thread", "log"] }
static_cell = "2.0"

esp32-hal = { version = "0.10", features = ["embassy", "embassy-time-timg0"] }
